// Generated by gencpp from file lab5_pkg/captureRequest.msg
// DO NOT EDIT!


#ifndef LAB5_PKG_MESSAGE_CAPTUREREQUEST_H
#define LAB5_PKG_MESSAGE_CAPTUREREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab5_pkg
{
template <class ContainerAllocator>
struct captureRequest_
{
  typedef captureRequest_<ContainerAllocator> Type;

  captureRequest_()
    : capture(false)  {
    }
  captureRequest_(const ContainerAllocator& _alloc)
    : capture(false)  {
  (void)_alloc;
    }



   typedef uint8_t _capture_type;
  _capture_type capture;




  typedef boost::shared_ptr< ::lab5_pkg::captureRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab5_pkg::captureRequest_<ContainerAllocator> const> ConstPtr;

}; // struct captureRequest_

typedef ::lab5_pkg::captureRequest_<std::allocator<void> > captureRequest;

typedef boost::shared_ptr< ::lab5_pkg::captureRequest > captureRequestPtr;
typedef boost::shared_ptr< ::lab5_pkg::captureRequest const> captureRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab5_pkg::captureRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab5_pkg::captureRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab5_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab5_pkg::captureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab5_pkg::captureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5_pkg::captureRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab5_pkg::captureRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5_pkg::captureRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab5_pkg::captureRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab5_pkg::captureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1511656c9b7347041e8df9246f87125";
  }

  static const char* value(const ::lab5_pkg::captureRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1511656c9b73470ULL;
  static const uint64_t static_value2 = 0x41e8df9246f87125ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab5_pkg::captureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab5_pkg/captureRequest";
  }

  static const char* value(const ::lab5_pkg::captureRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab5_pkg::captureRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool capture\n\
";
  }

  static const char* value(const ::lab5_pkg::captureRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab5_pkg::captureRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.capture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct captureRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab5_pkg::captureRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab5_pkg::captureRequest_<ContainerAllocator>& v)
  {
    s << indent << "capture: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.capture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB5_PKG_MESSAGE_CAPTUREREQUEST_H
