// Generated by gencpp from file lab5_pkg/capture.msg
// DO NOT EDIT!


#ifndef LAB5_PKG_MESSAGE_CAPTURE_H
#define LAB5_PKG_MESSAGE_CAPTURE_H

#include <ros/service_traits.h>


#include <lab5_pkg/captureRequest.h>
#include <lab5_pkg/captureResponse.h>


namespace lab5_pkg
{

struct capture
{

typedef captureRequest Request;
typedef captureResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct capture
} // namespace lab5_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lab5_pkg::capture > {
  static const char* value()
  {
    return "4fafc27449e87a2606a3a44304a19b34";
  }

  static const char* value(const ::lab5_pkg::capture&) { return value(); }
};

template<>
struct DataType< ::lab5_pkg::capture > {
  static const char* value()
  {
    return "lab5_pkg/capture";
  }

  static const char* value(const ::lab5_pkg::capture&) { return value(); }
};


// service_traits::MD5Sum< ::lab5_pkg::captureRequest> should match 
// service_traits::MD5Sum< ::lab5_pkg::capture > 
template<>
struct MD5Sum< ::lab5_pkg::captureRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lab5_pkg::capture >::value();
  }
  static const char* value(const ::lab5_pkg::captureRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab5_pkg::captureRequest> should match 
// service_traits::DataType< ::lab5_pkg::capture > 
template<>
struct DataType< ::lab5_pkg::captureRequest>
{
  static const char* value()
  {
    return DataType< ::lab5_pkg::capture >::value();
  }
  static const char* value(const ::lab5_pkg::captureRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lab5_pkg::captureResponse> should match 
// service_traits::MD5Sum< ::lab5_pkg::capture > 
template<>
struct MD5Sum< ::lab5_pkg::captureResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lab5_pkg::capture >::value();
  }
  static const char* value(const ::lab5_pkg::captureResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lab5_pkg::captureResponse> should match 
// service_traits::DataType< ::lab5_pkg::capture > 
template<>
struct DataType< ::lab5_pkg::captureResponse>
{
  static const char* value()
  {
    return DataType< ::lab5_pkg::capture >::value();
  }
  static const char* value(const ::lab5_pkg::captureResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LAB5_PKG_MESSAGE_CAPTURE_H
